### ISSUE TITLE
Broke "Duplucate tab" feature. 

### ISSUE THREAD

**Issue by ghost** [oinkin/treestyletab#6]
Not working duplicate tab feature, problem with this add-on. When it disabled - all working fine.
![2017-06-05 19-18-00](https://cloud.githubusercontent.com/assets/21217444/26792785/a08e7cae-4a2c-11e7-9477-ec2e58b87343.png)

**Comment by AlfredTheorin** [comment]
I have the same issue  and the same message as in your screenshot.

It is caused by version incompatibility between 'Tab Mix Plus 0.5.0.3' and 'Tree Style Tabs for Pale Moon 0.0.2'.

A workaround is to disable the following setting: Tab Mix Plus Options / Events (menu) / New Tabs (tab) / 'Open duplicated tabs next to original' (uncheck)

**Comment by zgwerby** [comment]
Thanx, working

**Comment by AlfredTheorin** [comment]
Screenshot for the setting mentioned in my previous comment.

![fix duplicate tab for palemoon with tst and tmp](https://user-images.githubusercontent.com/4907760/27174691-3fafb4a0-51bd-11e7-8c7f-e1a51aded729.png)

**Comment by oinkin** [comment]
Sorry guys but, per this extension's mission statement, there's no way that I'm going to hunt down bugs that involve interactions with extra extensions I don't use. Now that Github's actually sending me emails about this repository, I'll merge any pull requests you care to create.
